"""Auto-generated module + schema documentation, from validated metadata only.

``docs/MODULE_REGISTRY.md`` is *generated*, never hand-edited: every row comes
from a manifest that passed contract validation, from live SQLAlchemy
metadata, or from the migration ledger.  A doc that can drift out of sync with
the code is worse than no doc, so the generator refuses to invent content —
missing data is printed as ``—`` instead of being filled with prose.

Regenerate with::

    python tools/dbupdate.py docs
"""
from __future__ import annotations
import re
from datetime import datetime, timezone
from pathlib import Path

GENERATED_BANNER = (
    "<!-- GENERATED FILE - DO NOT EDIT\n"
    "     produced by app/services/dbupdate/docs.py (python tools/dbupdate.py docs)\n"
    "     source of truth: module.toml manifests, SQLAlchemy metadata, ams_schema_migration ledger\n"
    "-->"
)

MANUAL_SECTION_START = "<!-- MANUAL-NOTES-START -->"
MANUAL_SECTION_END = "<!-- MANUAL-NOTES-END -->"


def _cell(value) -> str:
    if value in (None, "", [], {}, ()):
        return "—"
    if isinstance(value, (list, tuple, set)):
        items = sorted(str(item) for item in value)
        return ", ".join(items) if items else "—"
    text = str(value).replace("|", "\\|").replace("\n", " ")
    return text or "—"


def generate(app=None, *, registry=None, write: bool = True) -> dict:
    """Build the registry document. Returns ``{path, changed, modules}``."""
    root = Path(app.root_path).parent if app is not None else Path(__file__).resolve().parents[3]
    if registry is None and app is not None:
        try:
            registry = app.extensions.get("ams_modules")
        except Exception:
            registry = None
    specs = sorted(registry.specs.values(), key=lambda s: (s.order, s.module_id)) if registry is not None else []

    core_tables, table_models = _metadata_tables()
    ledger_rows = []
    runs: list = []
    if app is not None:
        try:
            from app.services.dbupdate import ledger

            with app.app_context():
                # Read-only on purpose: generating a document must never create
                # tables in whatever database this process happens to point at.
                ledger.ensure_ledger(allow_create=False)
                ledger_rows = ledger.history(limit=200)
                runs = ledger.recent_runs(limit=10)
        except Exception:
            ledger_rows, runs = [], []

    lines: list[str] = [
        GENERATED_BANNER,
        "",
        "# AMS Module Registry (generated)",
        "",
        f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
        "",
        "Every module below was discovered through the contract in",
        "`docs/MODULE_CONTRACT.md`. This file is regenerated by",
        "`python tools/dbupdate.py docs`; edits here will be overwritten.",
        "",
        "## Modules",
        "",
        "| ID | Name | Version | Status | URL prefix | Tables | Nav | Migrations | Tests |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for spec in specs:
        lines.append(
            "| "
            + " | ".join(
                [
                    _cell(spec.module_id),
                    _cell(spec.name),
                    _cell(spec.version),
                    _cell(spec.status),
                    _cell(spec.url_prefix),
                    _cell(spec.tables),
                    _cell([nav.id for nav in spec.navigation]),
                    _cell([migration.version for migration in spec.migrations] + [f"data:{m.version}" for m in spec.data_migrations]),
                    _cell(spec.test_paths),
                ]
            )
            + " |"
        )
    if not specs:
        lines.append("| — | no modules discovered | — | — | — | — | — | — | — |")

    lines += ["", "## Module detail", ""]
    for spec in specs:
        permission_defaults = sorted(spec.permission_defaults.items()) if spec.permission_defaults else []
        feature_flags = sorted(spec.features.items()) if spec.features else []
        nav_pairs = [f"{nav.id} -> {nav.endpoint}" for nav in spec.navigation]
        migration_versions = [migration.version for migration in spec.migrations] + [
            f"data:{migration.version}" for migration in spec.data_migrations
        ]
        lines += [
            f"### `{spec.module_id}` — {spec.name}",
            "",
            f"- **Description:** {_cell(spec.description)}",
            f"- **Version:** {_cell(spec.version)}  **Status:** {_cell(spec.status)}  "
            f"**Contract:** schema_api {_cell(spec.schema_api)}",
            f"- **Source:** {_cell(spec.package)}  (manifest `{_cell(spec.manifest_path)}`, "
            f"discovered as `{_cell(spec.source)}`)",
            f"- **URL prefix:** {_cell(spec.url_prefix)}",
            f"- **Depends on:** {_cell(spec.depends_on)}",
            f"- **Routes:** {_cell(spec.expected_endpoints)}",
            f"- **Database tables:** {_cell(spec.tables)}",
            f"- **Model registry:** {_cell(spec.models_import)}",
            f"- **Permissions:** required {_cell(spec.permission_required)}; defaults {_cell(permission_defaults)}",
            f"- **Migrations:** {_cell(migration_versions)}",
            f"- **Health checks:** {_cell(spec.health_checks)}",
            f"- **Declared tests:** {_cell(spec.test_paths)}",
            f"- **Feature flags:** {_cell(feature_flags)}",
            f"- **Navigation:** {_cell(nav_pairs)}",
            "",
        ]
        if spec.migrations or spec.data_migrations:
            lines += [
                "| Migration | Kind | File | Destructive | Data validation | Checksum |",
                "|---|---|---|---|---|---|",
            ]
            for migration in list(spec.migrations) + list(spec.data_migrations):
                kind = "data" if migration in spec.data_migrations else "schema"
                lines.append(
                    f"| {_cell(migration.version)} | {_cell(kind)} | {_cell(migration.file)} | "
                    f"{_cell('yes' if migration.destructive else 'no')} | "
                    f"{_cell('yes' if migration.requires_data_validation else 'no')} | "
                    f"{_cell((migration.checksum or '')[:12])} |"
                )
            lines.append("")
        if spec.problems:
            lines += ["**Reported problems**", ""]
            for problem in spec.problems:
                lines.append(
                    f"- `{_cell(problem.severity)}` {_cell(problem.code)} at {_cell(problem.field)}: "
                    f"{_cell(problem.message)}" + (f" — {_cell(problem.hint)}" if problem.hint else "")
                )
            lines.append("")

    lines += [
        "## Navigation (module-declared)",
        "",
        "| ID | Label | Endpoint | Parent | Order | Permission | Module |",
        "|---|---|---|---|---|---|---|",
    ]
    nav_rows = 0
    if registry is not None:
        for item in registry.navigation(app):
            nav_rows += 1
            lines.append(
                f"| {_cell(item.get('id'))} | {_cell(item.get('label'))} | {_cell(item.get('endpoint'))} | "
                f"{_cell(item.get('parent'))} | {_cell(item.get('order'))} | {_cell(item.get('permission'))} | "
                f"{_cell(item.get('module'))} |"
            )
    if not nav_rows:
        lines.append("| — | core navigation is hard-coded in `templates/layout.html`; only modules that declare "
                     "`[navigation]` appear here | | | | | |")

    lines += [
        "",
        "## Database tables owned by modules",
        "",
        "| Table | Module | Columns | Primary key | Foreign keys |",
        "|---|---|---|---|---|",
    ]
    module_tables = {}
    for spec in specs:
        for table in spec.tables:
            module_tables[table] = spec.module_id
    for table in sorted(module_tables):
        info = table_models.get(table, {})
        lines.append(
            f"| `{_cell(table)}` | {_cell(module_tables[table])} | {_cell(info.get('columns'))} | "
            f"{_cell(info.get('primary_key'))} | {_cell(info.get('foreign_keys'))} |"
        )
    if not module_tables:
        lines.append("| — | no module owns tables yet | | | |")

    lines += [
        "",
        "## Declared revisions (from the module manifests)",
        "",
        "What each module *asks* to have applied.  Whether a revision has run",
        "against **this** database is machine-local state — read it with",
        "`python tools/dbupdate.py history`, or from the `ams_schema_migration`",
        "table / `instance/logs/migration-report.json`.  It is deliberately not",
        "printed here so this document stays reproducible from the repository",
        "alone instead of reflecting whichever database regenerated it last.",
        "",
        "| Revision | Module | Kind | Destructive | Data validation | File |",
        "|---|---|---|---|---|---|",
    ]
    data_refs = {
        (spec.module_id, ref.version) for spec in specs for ref in spec.data_migrations
    }

    def _kind_for(ref, spec) -> str:
        # the manifest's own declaration wins, then which list it sits in
        return ref.kind or ("data" if (spec.module_id, ref.version) in data_refs else "schema")
    declared = [
        (spec, ref)
        for spec in specs
        for ref in (list(spec.migrations) + list(spec.data_migrations))
    ]
    for spec, ref in sorted(declared, key=lambda pair: (pair[0].module_id, pair[1].version)):
        kind = _kind_for(ref, spec)
        lines.append(
            f"| {_cell(f'{spec.module_id}:{ref.version}')} | {_cell(spec.module_id)} | "
            f"{_cell(kind)} | {'yes' if ref.destructive else 'no'} | "
            f"{'required' if ref.requires_data_validation else '—'} | {_cell(ref.file)} |"
        )
    if not declared:
        lines.append("| — | no module declares revisions yet | | | | |")
    if ledger_rows or runs:
        applied = [row for row in ledger_rows if row.get("status") == "APPLIED"]
        lines += [
            "",
            (
                f"_Local snapshot at generation time (not authoritative): this database "
                f"recorded {len(applied)} applied revision(s) across {len(runs)} update run(s)._"
            ),
        ]

    lines += [
        "",
        "## Core application tables",
        "",
        f"{len(core_tables)} tables are declared by the application core (`models/`), documented in",
        "`docs/SKILLS_BOOK.md` § *DATABASE SCHEMA MAP*. Module-owned tables are listed above so the two",
        "never overlap: a module may not claim a core table.",
        "",
        MANUAL_SECTION_START,
        "### Operator notes",
        "",
        "Anything written between these two comment markers survives regeneration.",
        MANUAL_SECTION_END,
        "",
    ]
    content = "\n".join(lines) + "\n"
    target = root / "docs" / "MODULE_REGISTRY.md"
    changed = True
    if target.is_file():
        existing = target.read_text(encoding="utf-8")
        if _strip_generated(existing) == _strip_generated(content):
            changed = False
    if write and changed:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
    return {
        "path": str(target),
        "changed": changed if write else False,
        "modules": len(specs),
        "module_tables": len(module_tables),
        "ledger_rows": len(ledger_rows),
        "written": bool(write and changed),
    }


def _strip_generated(text: str) -> str:
    """Ignore the timestamp line (and preserve manual notes) when diffing."""
    body = re.sub(r"^Generated: .*$", "", text, flags=re.MULTILINE)
    return body.strip()


def _metadata_tables() -> tuple[list[str], dict[str, dict]]:
    info: dict[str, dict] = {}
    try:
        from models import db
    except Exception:
        return [], info
    tables = sorted(db.metadata.tables)
    for name, table in db.metadata.tables.items():
        try:
            info[name] = {
                "columns": len(table.columns),
                "primary_key": ", ".join(col.name for col in table.primary_key.columns),
                "foreign_keys": ", ".join(
                    sorted(
                        f"{fk.parent.name}→{fk.column.table.name}"
                        for constraint in table.foreign_key_constraints
                        for fk in constraint.elements
                        if fk.column is not None and fk.column.table is not None
                    )
                ),
            }
        except Exception:
            info[name] = {"columns": len(table.columns), "primary_key": "", "foreign_keys": ""}
    return tables, info
